name: Deploy Vite Project

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change to your desired Node.js version
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
        env:
          PATH: ${{ env.PATH }}

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the project
      - name: Build Project
        run: pnpm run build

      # Step 6: Deploy (Example for GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change to your build output directory if different
